CXX = g++
CXXFLAGS = -Wall -std=c++17
LIBS = -lSDL2

SRC = main.cpp Vector.cpp point.cpp line.cpp circle.cpp InputHandler.cpp UserWindow.cpp
OBJ = $(SRC:.cpp=.o)

TARGET = program

$(TARGET): $(OBJ)
	$(CXX) $(OBJ) -o $(TARGET) $(LIBS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)